config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :messages,      only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :images
  resources :images do
  member do
    get 'show_image'
  end
end
  root  'static_pages#home'
  match '/users/:id/image', as: 'image_user', to: 'users#image', via: 'get'
  match '/users/:id/message', as: 'message_user', to: 'users#message', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/auth',    to: 'sessions#auth',        via: 'get'
  match '/authing', to: 'sessions#authing',        via: 'post'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
      [<%= link_to "message", feed_item.user %>]
    </span>


    <span class="content">
    <%= feed_item.content %>
    </br>
    </br>
    </br>
    <%# Tagを切り出して，投稿者の画像と一致した場合のみ表示．途中で英字が入っている場合はreturnする%>
    <% 
      $tag = extraction_hashtag(feed_item.content) 
    %>
    <% $tag.each do |img| %>
      <%f = Image.find_by_id(img.delete("#"))%>
      <%if(f.nil?)%>
      <%else%>
        <% if(f.user_id == feed_item.user_id) %>
        <a href="<%= show_image_image_path(img.delete("#")) %>">#<%= img.delete("#") %>
          <%= image_tag show_image_image_path(img.delete("#")), class: "middle-img" %>
        </a>
        </br>
        <% end %>
      <% end %>
    <% end %>


    </span>


    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>

  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_message_form.html.erb
<%= form_for(@message) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new message..." %>
    <%= f.text_field :originator_id, :style => "display:none",:value => params[:id],:readonly => (true) %>
  </div>
  <%= f.submit "Send message", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user %>
</a>
<div class = "name-st">
	<%= current_user.name %>
</div>

<div class = "description-st">
	<%= current_user.description %>
</div>

<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>