config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :messages,      only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :images
  resources :images do
  member do
    get 'show_image'
  end
end
  root  'static_pages#home'
  match '/users/:id/image', as: 'image_user', to: 'users#image', via: 'get'
  match '/users/:id/message', as: 'message_user', to: 'users#message', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/auth',    to: 'sessions#auth',        via: 'get'
  match '/authing', to: 'sessions#authing',        via: 'post'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">

<div class="fv">
	<div class="rgh">
    Copyright 2007-2099 <a href="http://">KMD MERCENARY</a>, All Rights Reserved.
    </div>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
</div>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "kmd mercenary", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Box", image_user_path(current_user) %></li>
                <li><%= link_to "Message", message_user_path(current_user) %></li>
                <li><%= link_to "Profile", current_user %></li>

                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_js.html.erb
<script type="text/javascript">
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/js' %>
  </head>
  <body>

    <% if signed_in? %>

      <% if params[:controller] == "users" && params[:action] == "message"%>
        <div id="bg">
          <img src="/assets/low.jpg" alt="">
        </div>
      <% else %>
        <div id="bg">
          <img src="/assets/vw.jpg" alt="">
        </div>
      <% end %>    

    <% else %>

      <div id="bg">
        <img src="/assets/1.jpg" alt="">
      </div>
    
    <% end %>

<div class="front">
    <%= render 'layouts/header' %>

    <div class="container">

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%#= debug(params) if Rails.env.development? %>
    </div>

    <%= render 'layouts/footer' %>
</div>
  </body>
</html>